version: "3.7"
services:
  web:
    image: nginx:latest
    depends_on:
      - node1
      - node2
    # build:
    #context: ./nginx
    #dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  node1:
    build:
      context: ./node
      dockerfile: Dockerfile
      args:
        port: 3000
    restart: always
  node2:
    build:
      context: ./node
      dockerfile: Dockerfile
      args:
        port: 3001
    restart: always
