version: "3.7"
services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - node1
      - node2
    restart: always
    ports:
      - 80:80
  node1:
    build:
      context: ./node
      dockerfile: Dockerfile
      args:
        - PORT=3000
    restart: always
  node2:
    build:
      context: ./node
      dockerfile: Dockerfile
      args:
        - PORT=3001
    restart: always
