version: "3.7"
services:
  web:
    image: nginx:latest
    depends_on:
      - node1
      - node2
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./front/index.html:/var/www/html/index.html
  node1:
    build:
      context: ./node
      dockerfile: Dockerfile
      args:
        - PORT=3000
    restart: always
  node2:
    build:
      context: ./node
      dockerfile: Dockerfile
      args:
        - PORT=3001
    restart: always
